doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: symacl
                user: debian-sys-maint
                password: amRx7qUZjK7pAlA9
                host: 127.0.0.1
                server_version: '5.7'
                logging: '%kernel.debug%'
      # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
